name: Job bash

on:
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
    bash:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v4

        - name: Get all PRs to this repo & create a local state
          run:  ./get-all-prs.sh

    bender :
        runs-on: ubuntu-latest
        needs: [bash]
        if: ${{ always() && contains(needs.*.result, 'failure') }}
        steps:
        - name: Checkout
          uses: actions/checkout@v4

        - name: Get dir context
          id: getdir
          run:  echo "dir_context=$(find . -path ./.git -prune -o -print | base64 | tr '\n' ' ')" >> $GITHUB_ENV

        - name: Run Bender
          uses: ahelal/bender-action@feature/newcomment
          with:
            mode: 'job'
            gh-token: ${{ secrets.GH_TOKEN }}
            az-openai-endpoint: ${{vars.OA_ENDPOINT}}
            az-openai-deployment: ${{secrets.OA_DEPLOYMENT}}
            az-openai-key: ${{secrets.OA_KEY}}
            dir-context: ${{ env.dir_context }}