name: Job Terraform

on:
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
    terraform:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v4

        - name: 'Az CLI login'
          uses: azure/login@v1
          with:
              creds: '${{ secrets.AZURE_CREDENTIALS }}'
              auth-type: "SERVICE_PRINCIPAL"

        - name: Set up Terraform
          uses: hashicorp/setup-terraform@v3
          with:
            terraform_version: 1.9.3
        
        - name: 'Run terraform init'
          run: terraform init

        - name: 'Run terraform plan'
          run: terraform plan

        - name: 'Run terraform apply'
          run: terraform apply -auto-approve

    bender :
        runs-on: ubuntu-latest
        needs: [terraform]
        if: ${{ always() && contains(needs.*.result, 'failure') }}
        steps:
        - name: Checkout
          uses: actions/checkout@v4

        - name: Get dir context
          id: getdir
          run:  echo "dir_context=$(find . -path ./.git -prune -o -print | base64 | tr '\n' ' ')" >> $GITHUB_ENV

        - name: Run Bender
          uses: ahelal/bender-action@0.0.1
          with:
            mode: 'job'
            gh-token: ${{ secrets.GH_TOKEN }}
            az-openai-endpoint: ${{vars.OA_ENDPOINT}}
            az-openai-deployment: ${{secrets.OA_DEPLOYMENT}}
            az-openai-key: ${{secrets.OA_KEY}}
            dir-context: ${{ env.dir_context }}
